language: java
jdk: oraclejdk8

branches:
  except:
    - code-analysis

env:
  global:
    - MAVEN_OPTS="-Xms1024m -Xmx4g -Dmaven.repo.local=$HOME/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    - MAVEN_CLI_OPTS="--batch-mode --errors --fail-at-end --show-version"
    # DOCKER_USERNAME
    - secure: "gwyzZlahwziBgpMjPoUtT6qCTOeF8L1XXz4QBpCOz9v7j3coY7k7tQTS2Onv03lpinP3N2QtmCTKAODwpnkwO/KM/VDZZ9jpA6sYZvCLz7mzHb8kjiFZ0WVHSwsHtUrjpOSDhneQFEOmiDZTMdCxRRTDV4R1JDJaA6hM13OsZjQx2s4m5fM/mY/PkcwNy+UreyfJMn2Je9QVD6ye0/NbdPE+U9IBj0nmPtU93DD/mg5a3rahX/pn5D5yfNR2NsU18+HRR9qx+0mHknb7Hofk8dIaPk4HZj2LTRxTIFYpNAmA4vtWC+L2BHooD6yIisk91g/BoKNN/LEaeV6qctmEuXN06F2zjoFClcg3Oek5SXKswHviPMsjrQlcn7KdAcH/9QXGORVwKM0KsQhaktXff8gI6Ds0f4QAJHa7efm9dq4pD+/CKmNktmSW0PBakzdsfva2veOOaYU8730J++UNQ8AdYuzGvPVUzIvzYRx+KL0ZQP6d2sIpjQ2UAzd1Vu2VP55UtPShHgUa7dj/gbQVWLKXGcWJpCcIoi3tcGg+SLZW/E/NC6gOdGyuH0w1EU46kycxpv63KwFBvySv2XQ+DBfI4j1SA0UHTOXwzInj7P+hFYICBH+Ji3RELB6OyEKxMMZg+757euBbabs6k/sxrj0kdnBg89EZYebQx4pfeD4="
    # DOCKER_PASSWORD
    - secure: "cf+kYrLvsMtNNNdkUF5BK2NyZDJ3WwVtI1vKU1VQI/oSY8TyEctv0yzGiOFUCAKmgZhYnE1Ue6tEEKtVAkLV9gre+nbZo5jZQ0G+H1CvB0x187NsUD0wbjPeeWLZVn+bjQlqqFGolQDTOHvIecIU3OjSenyGO1mKzw9KjcQENd3v+qRE2mGDhxSdgtni5kcGDbnRw6DBJpkcfa9X30L7LrWlblhiYamugewiWqnVxKMDAiA0pIVS4Lr5ozgQ7q0MmnbBVMnI6jTTY/CuNRhu5Odi5G9m2IRK+XJh0QZCfLkUnHcVy+iJz3alt5soXk8X+u8OQ+I6LXoTpuQb4iWVUWKHc8QGR9P7ur2E5V1koM/Nw4hTyzwx8GbBDKuehxW5d4367Ty1Eu65Di4Xmd4lLrtKWSkieYF5Y3Z89fbDL0a1rdkDfpft+6yLSHZlhII3H9G4dJqZS6LXc54tPa9YiWTbuGP5duCfKu8EaO7QsGLU3Cvgdfth2mfUFabOBWOKSasn6eFWNxrm9CXGdPlB1aF4UMk+1fm7+zjGftiru7Mljx+3X4MDhOGZLVWKUkFcYDajnFXzScYMpvqI7SH0meYlGPsVj0wUVsd4LzU9THJJ76MHxNZzzUHYE2u9IKuPXcwLAKHoII8Hpi2tUX+3pkrUKO5JVNxFhkYokqe/bN8="

addons:
  sonarqube:
    organization: "keeps"
    token:
      secure: C05vsV0wQanl5de2Bg8rlByKmAF1T3b8x47gzQMy7/aABBNquLBBEVtBUjpz/XoyZrq82asizs6l8BD4lKx5m6uSRFRoQwWMb3oZlN2P6hZ+20sspSWwIHnQpBxJfm3wjOwIMb/dXH11QIyQeYypzsMzK6khRwvtlMBDXHqBBIIuTwYLCY/cjTtaRvUn17ni3rSVH5iikYktup51nTriXKDjHamtD/Uz/jEppPWPNJbGy3JO2dngajFY/QKrJ+H1Z2WCUg99MumhEf8QvcHrZGy7hS8GI1yktPInn41tip70YnDejRgzM78HVsdOctSJn7OF37eGeiapJbdoPl9N4WyrXFGp985gcE6mIt7v0YfBggynS14/o0WP0ZGi4zTQrQQsy8myGF4iig0ayE5zA/dahhr4EwcOLkM/eMDuPR+l3wk3p+dbaDY7W1+p45MY8Y3e02iJ394gkbq5RMowi4PmxQLAO1D1gG8WB0GeLif0vf+T9JMHIuXMeM+0oBJJGi5P5Tkxxcm+0QbIt+pEuP4EldYUDpVM++uOT7FPH7/PaYU8BZemPsk+IXaD/OuEK2OrLBtX2K++p7r45xqjD1QVWOZPvJK8vsZpTREBERzThdO2kqj0zDQtTihea7yJSdmqcCY/2c93GQfw0rEvfG6ZE1hQGFmMlC7cowPN+fc="


before_install:
  - sed -r "s/ARTIFACTORY_USER/$ARTIFACTORY_USER/g;s/ARTIFACTORY_PASS/$ARTIFACTORY_PASS/g" .travis/maven_settings.xml > $HOME/.m2/settings.xml

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - travis_wait 30 mvn $MAVEN_CLI_OPTS -Dtestng.groups="travis-ci" -Dlogback.configurationFile=logback-travis.xml -Dsonar.scm.disabled=true clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

deploy:
  provider: script
  script: .travis/deploy.sh
  all_branches: true

after_script:
  - rm $HOME/.m2/settings.xml

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache

notifications:
  slack:
    secure: M7jJ1dmO1cx//vgzY5UgE650Fe/lm21Dm8WLDXJfz66hmjQihoYCzW19Id/ySgPs/exjEvS1Lvxa4r4t5mgQOe+uPpQOZKEK3IfQ6h7zIv40Rbsa6mY9GaAW4x1Obji5a7HNGD7BQiolYDX1jmtBxOcSetesvL5iX1Bru0E/R78=
