language: java
dist: trusty
jdk: oraclejdk8

branches:
  except:
  - code-analysis

env:
  global:
  - MAVEN_OPTS="-Xms1024m -Xmx4g -Dmaven.repo.local=$HOME/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  - MAVEN_CLI_OPTS="--batch-mode --errors --fail-at-end --show-version"
  - secure: MJEtXaLMc6eP/4+enF/7oyT3+wZWT6bGJwyEOUjnOK8Silm83i5kpxdXy+5ItqPde1V78m8JXmhdQ46xL6HtQJlOrmKdHcnCRx8y8v1shBBOIivBiHxNtFS6iXfb7IODVUiXZxeSsunMKwbCqhfTcTBwsz2CiyZYRkSu39nXkUzcbT7SL5Aend3yx6xVJE1cn/M/fxV34JToSiBCXUrxkWjmo71667JU1JcORShKtWGaDArXkBUonWDNaqFyqY/HHCHgERWm++rZGn0kI/JPwcJr2AzPr29DgHMjVsQBzxLpZmXbVQTrYKymqRa5ZxuX6Tm/S3Wv7pLniRI6nG0HhF4LgTEz5+3TqeIolqCt68tmyv+O9RHpAgI/ek7Ao9OpRscgB5mprriQEzuzY8ZWS1bY38lIenGewuq3aPvwcyNBLwAMPPb7EWgG+KtraEZPqGccSwlPZGQeEwHZHcnyB1FzmkeuwyRzvCCMlfj34F06+E3KjSytmCM2s2bK3llH3jXJqlnjDDuuTqPhJvt7qTo9w49m+2Bi4678FjbaA4pOH1G+1z2rEAEp/heeJFUvnG02WXkx72eEpCqe1neGGME6zPsU0S5KbgARv74unR/bDPwu8QNNJ7WHizDMawIJ9WcBLz9NrZHRbLc5M1r01TMKLxEyVD1lzR78q/Fp1Q0=
  - secure: D2HdamaNWb0YJmvaFjf7HyamZcG+h5PMIYuwtiz0lAsFTBzs/hxC6e1RQx/RADmnd8LPxBTg4J4dp0k8v8ftb2yQANmydoF4qKezW5cvU2ZeeeT02Nw77OGeoQQGjSazZeRSyODgkhYzaOAZjNU+mmLg7g6sjEIGOrLZ6t/9MKmRVtmv/38OPKb7R0DuqpOQ7MIWO8hhFszjzUpAle6DYj9G9fZE8nHAKdEh4ukPoDlcYclWBqSS6xuk7S3ieJtFoVYB/T5PnM172Ocj5YoVKo8NjbFIuDOhtmAF7nKZNzXi6ztK9VBLYWPPdcoqhI8gJufJ6dumVjhCmN0W4ueJQTT4R/N7hNNoZpBvksFSJO6e7gxGvv8D29XZZJgRurd0R2uEXhTXm0myNx+RkG7EJS/Gmd7684Dn8ujYuMwnFpCt23dW5tmRBvnetGfeyCTcYJKaryURUPtysrwXp7xTE4K2rcxccaQX4b2kIB00avCXIJX0777QBq8xb6i5L7u7XQBj6FP6Pdg50KdFcM3E9PkxIt9aDMrPS4teXy3vnC1P/WO5FtXjmT/cFp4/299j4MHaoIJ4nlvOs6B2oOFb6VLld9uDttqQG33sPfDCZsZq0siaa0XJxAbXdT/Y7KVEUeyjGIU3G3Wt9ObIlofiUmstaDwR7aCCbqlZ6Pa4Szc=

addons:
  sonarqube:
    organization: keeps
    token:
      secure: C05vsV0wQanl5de2Bg8rlByKmAF1T3b8x47gzQMy7/aABBNquLBBEVtBUjpz/XoyZrq82asizs6l8BD4lKx5m6uSRFRoQwWMb3oZlN2P6hZ+20sspSWwIHnQpBxJfm3wjOwIMb/dXH11QIyQeYypzsMzK6khRwvtlMBDXHqBBIIuTwYLCY/cjTtaRvUn17ni3rSVH5iikYktup51nTriXKDjHamtD/Uz/jEppPWPNJbGy3JO2dngajFY/QKrJ+H1Z2WCUg99MumhEf8QvcHrZGy7hS8GI1yktPInn41tip70YnDejRgzM78HVsdOctSJn7OF37eGeiapJbdoPl9N4WyrXFGp985gcE6mIt7v0YfBggynS14/o0WP0ZGi4zTQrQQsy8myGF4iig0ayE5zA/dahhr4EwcOLkM/eMDuPR+l3wk3p+dbaDY7W1+p45MY8Y3e02iJ394gkbq5RMowi4PmxQLAO1D1gG8WB0GeLif0vf+T9JMHIuXMeM+0oBJJGi5P5Tkxxcm+0QbIt+pEuP4EldYUDpVM++uOT7FPH7/PaYU8BZemPsk+IXaD/OuEK2OrLBtX2K++p7r45xqjD1QVWOZPvJK8vsZpTREBERzThdO2kqj0zDQtTihea7yJSdmqcCY/2c93GQfw0rEvfG6ZE1hQGFmMlC7cowPN+fc="

before_install:
- sed -r "s/ORACLE_MAVEN_USERNAME/$ORACLE_MAVEN_USERNAME/g;s/ORACLE_MAVEN_PASSWORD/$ORACLE_MAVEN_PASSWORD/g;s/ARTIFACTORY_USER/$ARTIFACTORY_USER/g;s/ARTIFACTORY_PASS/$ARTIFACTORY_PASS/g" .travis/maven_settings.xml > $HOME/.m2/settings.xml

script:
- travis_wait 30 mvn $MAVEN_CLI_OPTS -Dtestng.groups="travis-ci" -Dlogback.configurationFile=logback-travis.xml
  -Dsonar.scm.disabled=true clean org.jacoco:jacoco-maven-plugin:prepare-agent install
  sonar:sonar

before_deploy:
- sed -ri "s/VERSION/$TRAVIS_BRANCH/g" .travis/descriptor.json
- sed -ri "s/RELEASED/`date "+%y-%d-%m"`/g" .travis/descriptor*.json

deploy:
  - provider: bintray
    file: .travis/descriptor-staging.json
    user: "006627"
    key:
      secure: rErT6sjqzP/3iop0MWkjeTbTMQs1V/rG0j9wC/GS3Kly1ylYslLgn7FMZAUM7owZNyFjJBC8fXxcSKkaadoK0J7L1AZ9qfao3/Q5wbrRgjdHYRq2OL1BHzeEprQrnCrocjpmsg6XBA48eNzJC5S780azQmkVecRbJdeU+jCylPZjufje6lVCI9wdKYS4CqLTikYq8Yhnap1BjmLCHduaFa8ohL0wTJ4V6CTxDkQHO3BIlZMd/fICQB1faPxeiGDtEgEUDkSzKqjyGlffI4Qv6OwL7H0Y6dzzp8pY7x+3GvEErNUiKQCvySexkaBlypVjwIZvsI9y+eInB5ATeHeqXX+m4conMTggJas1piZsxBi5gR5K2cADfGq4VaiPtkXDzp8CltUB6XDDbaiEdLzDWbDZ+JKHfSkUCLel5q/Ua8emX8rFlPxYGHyj64rKefnnvJgmZkHzvFj8kdTmq9w697ZG1s5tohWwGECcnQX7VQ3Z3KSomlPaOWa5ykJVA5DupaYnaajzjq0AGbadaTLJSp1tgH48q3nOaDbTeNnn7iwk7fBNAP9MmERF+j1dlsbwSB408pQlyOq3ZlagotnKusjJJ2z/xjddEJL2/Fis2quhZOVOIzHshbwfI4szCOz4rWie2D546asgstiRdr6sDWY88Cc4hgSfiBYLUmJ4DZk=
    skip_cleanup: true
    on:
      branch: staging

  - provider: bintray
    file: .travis/descriptor.json
    user: "006627"
    key:
      secure: rErT6sjqzP/3iop0MWkjeTbTMQs1V/rG0j9wC/GS3Kly1ylYslLgn7FMZAUM7owZNyFjJBC8fXxcSKkaadoK0J7L1AZ9qfao3/Q5wbrRgjdHYRq2OL1BHzeEprQrnCrocjpmsg6XBA48eNzJC5S780azQmkVecRbJdeU+jCylPZjufje6lVCI9wdKYS4CqLTikYq8Yhnap1BjmLCHduaFa8ohL0wTJ4V6CTxDkQHO3BIlZMd/fICQB1faPxeiGDtEgEUDkSzKqjyGlffI4Qv6OwL7H0Y6dzzp8pY7x+3GvEErNUiKQCvySexkaBlypVjwIZvsI9y+eInB5ATeHeqXX+m4conMTggJas1piZsxBi5gR5K2cADfGq4VaiPtkXDzp8CltUB6XDDbaiEdLzDWbDZ+JKHfSkUCLel5q/Ua8emX8rFlPxYGHyj64rKefnnvJgmZkHzvFj8kdTmq9w697ZG1s5tohWwGECcnQX7VQ3Z3KSomlPaOWa5ykJVA5DupaYnaajzjq0AGbadaTLJSp1tgH48q3nOaDbTeNnn7iwk7fBNAP9MmERF+j1dlsbwSB408pQlyOq3ZlagotnKusjJJ2z/xjddEJL2/Fis2quhZOVOIzHshbwfI4szCOz4rWie2D546asgstiRdr6sDWY88Cc4hgSfiBYLUmJ4DZk=
    skip_cleanup: true
    on:
      tags: true

after_script:
- rm $HOME/.m2/settings.xml

after_deploy:
  - .travis/trigger-travis-build.sh

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

notifications:
  slack:
    secure: M7jJ1dmO1cx//vgzY5UgE650Fe/lm21Dm8WLDXJfz66hmjQihoYCzW19Id/ySgPs/exjEvS1Lvxa4r4t5mgQOe+uPpQOZKEK3IfQ6h7zIv40Rbsa6mY9GaAW4x1Obji5a7HNGD7BQiolYDX1jmtBxOcSetesvL5iX1Bru0E/R78=
