version: '3'
services:
  dbvtk:
    image: keeps/dbvtk:latest
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      # development option
      - COPY_APP_ON_STARTUP=${COPY_APP_ON_STARTUP}
      - JPDA_ADDRESS=5005
      - JPDA_TRANSPORT=dt_socket
      - "SOLR_ZOOKEEPER_HOSTS=solr:9983"
    volumes:
      # folder in which *.siard files should be dropped so they can be accessed from inside the server
      # You can override variables using environment, defaults are at .env, example:
      # SIARD=/path/to/folder/with/siard/files docker-compose up
      - ${SIARD}:/siard:ro
      - ${PROJECT}:/ROOT:ro

      # configuration overrides
      - ./config/logback.xml:/dbvtk/config/logback.xml:ro
    command: catalina.sh jpda run
    depends_on:
      - solr
  solr:
    image: solr:7.5
    ports:
      - 8983:8983
    command: -c # Use cloud mode
