version: '3.2'
services:
  dbvtk:
    image: keeps/dbvtk:latest
    ports:
      - 8080:8080
    environment:
      - SOLR_ZOOKEEPER_HOSTS=solr:9983
    volumes:
      # folder in which *.siard files should be dropped so they can be accessed from inside the server
      # You can override variables using environment, defaults are at .env, example:
      # SIARD=/path/to/folder/with/siard/files docker-compose up
      - ${SIARD}:/siard:ro

      # configuration overrides
      # - ./config/logback.xml:/dbvtk/config/logback.xml:ro
      # - ./config/dbvtk-viewer.properties:/dbvtk/config/dbvtk-viewer.properties:ro
    depends_on:
      - solr
  solr:
    image: solr:7.7
    ports:
      - 8983:8983
    command: -c # Use cloud mode
