name: "CI"

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
      - name: Cache
        uses: actions/cache@v1.0.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Notify slack success
        if: success()
        id: slack # IMPORTANT: reference this step ID value in future Slack steps
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_DBPTK_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: dbptk
          status: STARTING
          color: warning
      - name: Build DBPTK-UI
        run: mvn $MAVEN_CLI_OPTS -Dtestng.groups="travis-ci" clean org.jacoco:jacoco-maven-plugin:prepare-agent install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_DBPTK_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: dbptk
          status: SUCCESS
          color: good
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_DBPTK_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: dbptk
          status: FAILED
          color: danger

